const imageMap: Record<string, any> = {
  airplane: require("@/assets/images/card-images/airplane.png"),
  bathtub: require("@/assets/images/card-images/bathtub.png"),
  birthday: require("@/assets/images/card-images/birthday.png"),
  cowboy: require("@/assets/images/card-images/cowboy.png"),
  cupcake: require("@/assets/images/card-images/cupcake.png"),
  donut: require("@/assets/images/card-images/donut.png"),
  flashlight: require("@/assets/images/card-images/flashlight.png"),
  football: require("@/assets/images/card-images/football.png"),
  "french fries": require("@/assets/images/card-images/frenchfries.png"),
  "hot dog": require("@/assets/images/card-images/hotdog.png"),
  "ice cream": require("@/assets/images/card-images/icecream.png"),
  mushroom: require("@/assets/images/card-images/mushroom.png"),
  outside: require("@/assets/images/card-images/outside.png"),
  playground: require("@/assets/images/card-images/playground.png"),
  popcorn: require("@/assets/images/card-images/popcorn.png"),
  rainbow: require("@/assets/images/card-images/rainbow.png"),
  snowman: require("@/assets/images/card-images/snowman.png"),
  sunshine: require("@/assets/images/card-images/sunshine.png"),
  toothbrush: require("@/assets/images/card-images/toothbrush.png"),
};
export default imageMap;

export const audioMap: Record<string, any> = {
  airplane: require("@/assets/audio/airplane.mp3"),
  bathtub: require("@/assets/audio/bathtub.mp3"),
  birthday: require("@/assets/audio/birthday.mp3"),
  cowboy: require("@/assets/audio/cowboy.mp3"),
  cupcake: require("@/assets/audio/cupcake.mp3"),
  donut: require("@/assets/audio/donut.mp3"),
  flashlight: require("@/assets/audio/flashlight.mp3"),
  football: require("@/assets/audio/football.mp3"),
  "french fries": require("@/assets/audio/frenchfries.mp3"),
  "hot dog": require("@/assets/audio/hotdog.mp3"),
  "ice cream": require("@/assets/audio/icecream.mp3"),
  mushroom: require("@/assets/audio/mushroom.mp3"),
  outside: require("@/assets/audio/outside.mp3"),
  playground: require("@/assets/audio/playground.mp3"),
  popcorn: require("@/assets/audio/popcorn.mp3"),
  rainbow: require("@/assets/audio/rainbow.mp3"),
  snowman: require("@/assets/audio/snowman.mp3"),
  sunshine: require("@/assets/audio/sunshine.mp3"),
  toothbrush: require("@/assets/audio/toothbrush.mp3"),
};
