const imageMap: Record<string, any> = {
  airplane: require("../../assets/images/card-images/airplane.png"),
  bathtub: require("../../assets/images/card-images/bathtub.png"),
  birthday: require("../../assets/images/card-images/birthday.png"),
  cowboy: require("../../assets/images/card-images/cowboy.png"),
  cupcake: require("../../assets/images/card-images/cupcake.png"),
  donut: require("../../assets/images/card-images/donut.png"),
  flashlight: require("../../assets/images/card-images/flashlight.png"),
  football: require("../../assets/images/card-images/football.png"),
  "french fries": require("../../assets/images/card-images/frenchfries.png"),
  "hot dog": require("../../assets/images/card-images/hotdog.png"),
  "ice cream": require("../../assets/images/card-images/icecream.png"),
  mushroom: require("../../assets/images/card-images/mushroom.png"),
  outside: require("../../assets/images/card-images/outside.png"),
  playground: require("../../assets/images/card-images/playground.png"),
  popcorn: require("../../assets/images/card-images/popcorn.png"),
  rainbow: require("../../assets/images/card-images/rainbow.png"),
  snowman: require("../../assets/images/card-images/snowman.png"),
  sunshine: require("../../assets/images/card-images/sunshine.png"),
  toothbrush: require("../../assets/images/card-images/toothbrush.png"),
};
export default imageMap;
